version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: onegin-stremio_server_1
      APP_PORT: 11470
      PROXY_AUTH_ADD: "false"

  server:
    image: stremio/server:v4.21.2
    restart: on-failure
    environment:
      NO_CORS: "1"
      APP_PATH: /root/.stremio-server
    volumes:
      - ${APP_DATA_DIR}/data:/root/.stremio-server
    ports:
      - "12470:12470"
