version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: onegin-torrserver-un_server_1
      APP_PORT: 8090

  server:
    image: debian:bookworm-slim
    restart: on-failure
    environment:
      MATRIX_TAG: bylampa_MatriX.145.UN
      TS_PORT: 8090
      TS_PATH: /opt/ts/config
      TS_TORRENTSDIR: /opt/ts/torrents
    volumes:
      - ${APP_DATA_DIR}/data:/opt/ts
      - ./start.sh:/usr/local/bin/start.sh:ro
    entrypoint: ["/usr/local/bin/start.sh"]
